"""modelagem inicial

Revision ID: 376f5b6773fb
Revises: 
Create Date: 2026-09-27 21:45:00.305373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '376f5b6773fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('tipo', sa.Enum('RECEITA', 'DESPESA', name='tipolancamento'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_usuario_id'), 'categorias', ['usuario_id'], unique=False)
    op.create_table('contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('moeda', sa.String(length=3), server_default='BRL', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contas_usuario_id'), 'contas', ['usuario_id'], unique=False)
    op.create_table('fontes_renda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fontes_renda_usuario_id'), 'fontes_renda', ['usuario_id'], unique=False)
    op.create_table('regras_recorrencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('fonte_renda_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('RECEITA', 'DESPESA', name='tipolancamento'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('frequencia', sa.Enum('MENSAL', 'SEMANAL', name='frequenciarecorrencia'), nullable=False),
    sa.Column('dia_referencia', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('ativa', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['fonte_renda_id'], ['fontes_renda.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regras_recorrencia_usuario_id'), 'regras_recorrencia', ['usuario_id'], unique=False)
    op.create_table('transferencias_entre_contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_origem_id', sa.Integer(), nullable=False),
    sa.Column('conta_destino_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conta_destino_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['conta_origem_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transferencias_entre_contas_conta_destino_id'), 'transferencias_entre_contas', ['conta_destino_id'], unique=False)
    op.create_index(op.f('ix_transferencias_entre_contas_conta_origem_id'), 'transferencias_entre_contas', ['conta_origem_id'], unique=False)
    op.create_index(op.f('ix_transferencias_entre_contas_data'), 'transferencias_entre_contas', ['data'], unique=False)
    op.create_table('lancamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('fonte_renda_id', sa.Integer(), nullable=True),
    sa.Column('regra_recorrencia_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('RECEITA', 'DESPESA', name='tipolancamento'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['fonte_renda_id'], ['fontes_renda.id'], ),
    sa.ForeignKeyConstraint(['regra_recorrencia_id'], ['regras_recorrencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lancamentos_categoria_id'), 'lancamentos', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_lancamentos_conta_id'), 'lancamentos', ['conta_id'], unique=False)
    op.create_index(op.f('ix_lancamentos_data'), 'lancamentos', ['data'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lancamentos_data'), table_name='lancamentos')
    op.drop_index(op.f('ix_lancamentos_conta_id'), table_name='lancamentos')
    op.drop_index(op.f('ix_lancamentos_categoria_id'), table_name='lancamentos')
    op.drop_table('lancamentos')
    op.drop_index(op.f('ix_transferencias_entre_contas_data'), table_name='transferencias_entre_contas')
    op.drop_index(op.f('ix_transferencias_entre_contas_conta_origem_id'), table_name='transferencias_entre_contas')
    op.drop_index(op.f('ix_transferencias_entre_contas_conta_destino_id'), table_name='transferencias_entre_contas')
    op.drop_table('transferencias_entre_contas')
    op.drop_index(op.f('ix_regras_recorrencia_usuario_id'), table_name='regras_recorrencia')
    op.drop_table('regras_recorrencia')
    op.drop_index(op.f('ix_fontes_renda_usuario_id'), table_name='fontes_renda')
    op.drop_table('fontes_renda')
    op.drop_index(op.f('ix_contas_usuario_id'), table_name='contas')
    op.drop_table('contas')
    op.drop_index(op.f('ix_categorias_usuario_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###

